{{- if .Values.gateway.enabled }}
{{- if .Values.gateway.loadBalancer.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway
    app.kubernetes.io/name: {{ include "gatewayName" . }}
  name: {{ include "gatewayName" . }}
  {{- with .Values.gateway.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.gateway.ports.http }}
  selector:
    app: gateway
    app.kubernetes.io/name: {{ include "gatewayName" . }}
{{- end }}
{{- end }}
