{{- if .Values.kmsSCAdmin.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: kms-sc-admin
  name: {{ include "kmsSCAdminName" . }}-config
data:
  import-wallets.sh: |
    #!/bin/sh
    set -e
    {{- if .Values.kmsWallets.keyring.create }}
    # Initialize the keyring
    if ! (echo "$KEYRING_PASSWORD" | wasmd keys show rpc); then
      (echo "$KEYRING_PASSWORD"; echo "$KEYRING_PASSWORD") | wasmd keys add rpc --no-backup
    fi
    {{- end }}
    echo "loading keys into in the ${WASMD_KEYRING_DIR} keystore"
    for directory in "/keystore" "/addon-keystore"; do
      for key in $directory/*.mnemonic; do
        if [ -f "$key" ]; then
          echo "loading key from ${key}"
          (echo $(cat $key){{ if .Values.kmsWallets.keyring.create }}; echo $KEYRING_PASSWORD{{ end }}) | wasmd keys add "$(basename $key .mnemonic)" --recover
        fi
      done
    done
    echo "keys imported in keystore"
    # Keep the pod running
    tail -f /dev/null
{{- end -}}
