apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-anvil-node
spec:
  serviceName: {{ .Release.Name }}-anvil-node
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-anvil-node
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-anvil-node
    spec:
      containers:
        - name: anvil-node
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          command: ["anvil"]
          env:
            - name: MNEMONIC
              value: {{ .Values.network.mnemonic }}
          args:
            - "--block-time"
            - "{{ .Values.network.blockTime }}"
            - "--host"
            - "{{ .Values.network.host }}"
            - "--port"
            - "{{ .Values.port }}"
            - "--chain-id"
            - "{{ .Values.network.chainId }}"
            - "--accounts"
            - "{{ .Values.network.accounts }}"
            - "--mnemonic"
            - "$(MNEMONIC)"
          ports:
            - containerPort: {{ .Values.port }}
          volumeMounts:
          - name: anvil-chain-data
            mountPath: /home/foundry/.foundry/anvil
  volumeClaimTemplates:
  - metadata:
      name: anvil-chain-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.storage.size }}