apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: kms-threshold-staging-mutate-pod
spec:
  validationFailureAction: Audit
  rules:
    - name: replace-service-account-name
      match:
        any:
          - resources:
              kinds:
                - Pod
              names:
                - "kms-threshold-staging-[0-9]"
      preconditions:
        any:
        - key: "{{ request.object.spec.serviceAccountName }}"
          operator: NotEquals
          value: ""
      mutate:
        patchStrategicMerge:
          spec:
            serviceAccountName: "{{request.object.metadata.name}}"

    - name: replace-configmap-names-init
      match:
        any:
          - resources:
              kinds:
                - Pod
              names:
                - "kms-threshold-staging-[0-9]"
      preconditions:
        any:
        - key: "{{ request.object.spec.initContainers[] }}"
          operator: NotEquals
          value: []
      mutate:
        foreach:
        - list: "request.object.spec.initContainers"
          patchStrategicMerge:
            spec:
              initContainers:
              - name: "{{ element.name }}"
                envFrom:
                - configMapRef:
                    name: "{{request.object.metadata.name}}"

    - name: replace-configmap-names-containers
      match:
        any:
          - resources:
              kinds:
                - Pod
              names:
                - "kms-threshold-staging-[0-9]"
      preconditions:
        any:
        - key: "{{ request.object.spec.containers[] }}"
          operator: NotEquals
          value: []
      mutate:
        foreach:
        - list: "request.object.spec.containers"
          patchStrategicMerge:
            spec:
              containers:
              - name: "{{ element.name }}"
                envFrom:
                - configMapRef:
                    name: "{{request.object.metadata.name}}"