#export ZAMA_AI_USERNAME=user
#export ZAMA_AI_PASSWORD=pass
repositories:
#  - name: zama-ai
#    url: ghcr.io/zama-ai/helm-charts
#    oci: true
releases:
  - name: kms-blockchain
    namespace: kms-centralized
    chart: "../../charts/kms-blockchain"
    #chart: zama-ai/kms-blockchain
    #version:
    values:
      - kmsBlockchainNetworkSetup:
          validatorCount: 1
        kmsBlockchainValidator:
          replicas: 1

  - name: kms-sc-deploy
    chart: "../../charts/kms-sc-deploy"
    #chart: zama-ai/kms-sc-deploy
    #version:
    namespace: kms-centralized
    values:
      - centralized-kms-sc-deploy-values.yaml
    needs:
      - kms-blockchain

  - name: kms-service
    chart: "../../charts/kms-service"
    #chart: zama-ai/kms-service
    #version:
    namespace: kms-centralized
    values:
      - centralized-kms-service-values.yaml
      - minio:
          enabled: true
    needs:
      - kms-sc-deploy

  - name: kv-store
    chart: "../../charts/gateway"
    #chart: zama-ai/gateway
    #version:
    namespace: kms-centralized
    values:
      - centralized-kv-store-values.yaml
    needs:
      - kms-service
