nodeSelector: []
affinity: []
tolerations: []

gateway:
  enabled: true
  nameOverride:
  image:
    name: ghcr.io/zama-ai/kms-blockchain-gateway
    tag: v0.9.0-rc38
  storage:
    storageClassName: gp3
    capacity: 100Gi
  replicas: 1
  config:
    mode: threshold
    listenerType: COPROCESSOR
    # FHEVM
    coprocessorURL: "http://coprocessor-server:50051"
    fhevmFullNodeAddress: "coprocessor-geth-node:8546"
    fhevmFullNodeAddressHTTP: "coprocessor-geth-node:8545"
    chainId: "11155111"
    # KMS
    coreAddresses: '["http://kms-threshold-1-threshold-core.kms-threshold.svc.cluster.local:50100", "http://kms-threshold-2-threshold-core.kms-threshold.svc.cluster.local:50100", "http://kms-threshold-3-threshold-core.kms-threshold.svc.cluster.local:50100", "http://kms-threshold-4-threshold-core.kms-threshold.svc.cluster.local:50100"]'
    kmsBlockchainValidatorRPCAddress: "kms-blockchain-validator.kms-threshold.svc.cluster.local:26657"
    kmsBlockchainValidatorGRPCAddress: "kms-blockchain-validator.kms-threshold.svc.cluster.local:9090"
    kvStoreURL: "http://kv-store-kv-store.kms-threshold.svc.cluster.local:8088"
    kmsBuckets: []
    ascAddress: ""
    cscAddress: ""
    kmsKeyId: ""
    crsId2048: ""
  env:
    - name: GATEWAY__ETHEREUM__ORACLE_PREDEPLOY_ADDRESS
      valueFrom:
        configMapKeyRef:
          name: coprocessor-scs
          key: gateway.address
    - name: GATEWAY__ETHEREUM__KMSVERIFIER_VC_ADDRESS
      valueFrom:
        configMapKeyRef:
          name: coprocessor-scs
          key: kmsverifier.address
    - name: GATEWAY__ETHEREUM__ACL_ADDRESS
      valueFrom:
        configMapKeyRef:
          name: coprocessor-scs
          key: acl.address
    - name: GATEWAY__ETHEREUM__COPROCESSOR_API_KEY
      valueFrom:
        secretKeyRef:
          name: coprocessor-api-key
          key: coprocessor-api-key
    - name: GATEWAY__ETHEREUM__RELAYER_KEY
      valueFrom:
        secretKeyRef:
          name: coprocessor-keys
          key: gateway-relayer.key
    - name: GATEWAY__KMS__MNEMONIC
      valueFrom:
        secretKeyRef:
          name: kms-gateway-keys
          key: gateway-sepolia.mnemonic
    - name: GATEWAY__BLOCKCHAIN_SIGNKEY__MNEMONIC
      valueFrom:
        secretKeyRef:
          name: kms-gateway-keys
          key: gateway-sepolia.mnemonic
  service:
    annotations:
  loadBalancer:
    enabled: false
    hostnames:
      - gateway.example.com
  ingress:
    enabled: true
    # https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/ingress/annotations/
    annotations: []
  ports:
    http: "7077"
  wallet:
    create: true
    image:
      name: ghcr.io/zama-ai/wasmd-utils
      tag: 0.1.1
    names:
      - gateway-sepolia
    secret:
      name: kms-gateway-keys

kvStore:
  enabled: true
  nameOverride:
  image:
    name: ghcr.io/zama-ai/kms-blockchain-gateway
    tag: v0.9.0-rc38
  service:
    annotations:
  storage:
    storageClassName: gp3
    capacity: 100Gi
  replicas: 1
  config:
    coreAddresses: '["http://kms-threshold-1-threshold-core.kms-threshold.svc.cluster.local:50100", "http://kms-threshold-2-threshold-core.kms-threshold.svc.cluster.local:50100", "http://kms-threshold-3-threshold-core.kms-threshold.svc.cluster.local:50100", "http://kms-threshold-4-threshold-core.kms-threshold.svc.cluster.local:50100"]'
  ports:
    rpc: "8088"

tracing:
  endpoint: ""

rustLog: info
