{{- if .Values.kmsCoreClient.enabled -}}
# {{- $peersIDList := untilStep (default 1 .Values.kmsPeers.id | int) (.Values.kmsPeers.count | add1 | int) 1  }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: kms-core-client
    app.kubernetes.io/name: {{ include "kmsCoreClientName" . }}
  name: {{ include "kmsCoreClientName" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kms-core-client
  template:
    metadata:
      labels:
        app: kms-core-client
        app.kubernetes.io/name: {{ include "kmsCoreClientName" . }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: kms-core-client
          image: {{ .Values.kmsCoreClient.image.name }}:{{ .Values.kmsCoreClient.image.tag }}
          command: ["/bin/sh"]
          args:
            - -c
            - |
              kms-core-client
          env:
            - name: CORE_CLIENT__S3_ENDPOINT
              value: "{{ if .Values.minio.enabled }}http://minio:9000/{{ .Values.kmsCore.publicVault.s3.bucket }}{{ else }}https://zama-zws-dev-kms-party-kms-threshold-staging-fwz7w.s3.{{ .Values.kmsCore.aws.region }}.amazonaws.com{{ end }}/{{ .Values.kmsCore.publicVault.s3.path }}"
            - name: CORE_CLIENT__OBJECT_FOLDER
              value: '[{{ if .Values.kmsCore.thresholdMode.enabled }}{{ range $i, $peer := .Values.kmsCore.thresholdMode.peersList }}{{- if $i -}},{{ end }}"PUB-p{{-  $peer.id  -}}"{{- end }}{{ else }}"PUB"{{ end }}]'
            - name: CORE_CLIENT__CORE_ADDRESSES
              value: '[{{ range $i, $peer := .Values.kmsCore.thresholdMode.peersList }}{{- if $i -}},{{ end }}"{{-  $peer.address }}:{{-  $.Values.kmsCore.ports.client  -}}"{{- end }}]'
            - name: CORE_CLIENT__NUM_MAJORITY
              value: '{{ .Values.kmsCoreClient.num_majority | int | quote }}'
            - name: CORE_CLIENT__NUM_RECONSTRUCT
              value: '{{ .Values.kmsCoreClient.num_reconstruct | int | quote }}'
            - name: CORE_CLIENT__DECRYPTION_MODE
              value: '{{ .Values.kmsCoreClient.decryption_mode | quote }}'
      imagePullSecrets:
        - name: registry-credentials
      {{- with .Values.kmsCoreClient.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kmsCoreClient.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kmsCoreClient.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
