{{- if .Values.kmsCoreClient.enabled -}}
{{- $kmsCoreName := include "kmsCoreName" . }}
{{- $peersIDList := untilStep (default 1 .Values.kmsPeers.id | int) (.Values.kmsPeers.count | add1 | int) 1  }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: kms-core-client
    app.kubernetes.io/name: {{ include "kmsCoreClientName" . }}
  name: {{ include "kmsCoreClientName" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kms-core-client
  template:
    metadata:
      labels:
        app: kms-core-client
        app.kubernetes.io/name: {{ include "kmsCoreClientName" . }}
      {{ include "kmsService.clientPodSpec" . | nindent 6 }}
      {{- with .Values.kmsCoreClient.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kmsCoreClient.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kmsCoreClient.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
