{{- if .Values.kmsCoreClientTesting.enabled -}}
{{- $kmsCoreName := include "kmsCoreName" . }}
{{- $peersIDList := untilStep (default 1 .Values.kmsPeers.id | int) (.Values.kmsPeers.count | add1 | int) 1  }}
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: kms-core-client-testing
    app.kubernetes.io/name: {{ include "kmsCoreClientTestingName" . }}
  name: {{ include "kmsCoreClientTestingName" . }}
spec:
  schedule: {{ .Values.kmsCoreClientTesting.schedule }}
  jobTemplate:
    {{ include "kmsService.clientPodSpec" . | nindent 4 }}
        command:
          - /app/load-core-client-testing-config.sh
    envFrom:
      - configMapRef:
          name: {{ .Values.kmsCoreClient.envFrom.configmap.name }}
    volumeMounts:
      - mountPath: /app/load-core-client-testing-config.sh
        subPath: load-core-client-testing-config.sh
        name: config
  imagePullSecrets:
    - name: registry-credentials
  volumes:
    - name: config
      configMap:
        name: {{ include "kmsCoreClientTestingName" . }}-config
        defaultMode: 0777
        items:
          - key: load-core-client-testing-config.sh
            path: load-core-client-testing-config.sh
  {{- with .Values.kmsCoreClient.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .Values.kmsCoreClient.affinity }}
  affinity:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .Values.kmsCoreClient.tolerations }}
  tolerations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
{{- end -}}
