{{- if .Values.kmsCoreClientTesting.enabled -}}
{{- $kmsCoreName := include "kmsCoreName" . }}
{{- $peersIDList := untilStep (default 1 .Values.kmsPeers.id | int) (.Values.kmsPeers.count | add1 | int) 1  }}
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: kms-core-client-testing
    app.kubernetes.io/name: {{ include "kmsCoreClientTestingName" . }}
  name: {{ include "kmsCoreClientTestingName" . }}
spec:
  schedule: {{ .Values.kmsCoreClientTesting.schedule }}
  jobTemplate:
    {{ template "kmsService.clientPodSpec" . }}
    {{- with .Values.kmsCoreClientTesting.nodeSelector }}
    nodeSelector:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.kmsCoreClientTesting.affinity }}
    affinity:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.kmsCoreClientTesting.tolerations }}
    tolerations:
      {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end -}}
