config:
  enabled: true
  image:
    name: ghcr.io/zama-ai/kube-utils
    tag: 0.1.0
  coprocessorKey:
    secret:
      name: coprocessor-key
      key: coprocessor.hex
  apiKey:
    secret:
      name: coprocessor-api-key
      key: coprocessor-api-key
  database:
    secret:
      name: coprocessor-db-url
      key: coprocessor-db-url
      value: "postgresql://postgres:postgres@postgresql:5432/coprocessor"

dbMigration:
  enabled: true
  image:
    name: ghcr.io/zama-ai/fhevm-db-migration
    tag: v0.1.2
  env:
    - name: CHAIN_ID
      value: "12345"
    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: coprocessor-db-url
          key: coprocessor-db-url
    - name: TENANT_API_KEY
      valueFrom:
        secretKeyRef:
          name: coprocessor-api-key
          key: coprocessor-api-key
  insertInitContainer:
    pksURL: http://minio:9000/kms-public/kms/PUB/PublicKey/d74037feb1394aec0eb724afc4a690e16a0203eb1dc868de08179f2e4828f335
    sksURL: http://minio:9000/kms-public/kms/PUB/ServerKey/812b602c11693dda4bfa68db78269849972b6f1920a725a98fc78cf619a6ab5f
    publicParamsURL: http://minio:9000/kms-public/kms/PUB/CRS/e4e3f0deef6492bde2fac3f2c698112ace878d4a3656b272197ed332391c48fa

server:
  enabled: true
  nameOverride:
  image:
    name: ghcr.io/zama-ai/fhevm-coprocessor
    tag: v0.7.0-rc0
  replicas: 1
  env:
    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: coprocessor-db-url
          key: coprocessor-db-url
    - name: TENANT_API_KEY
      valueFrom:
        secretKeyRef:
          name: coprocessor-api-key
          key: coprocessor-api-key
    - name: ACL_CONTRACT_ADDRESS
      value: "0x05fD9B5EFE0a996095f42Ed7e77c390810CF660c"
    - name: INPUT_VERIFIER_ADDRESS
      value: "0xa1880e99d86F081E8D3868A8C4732C8f65dfdB11"
  args:
    - --run-server
    - --server-addr=0.0.0.0:50051
    - --coprocessor-private-key=/accounts/coprocessor.hex
  ports:
    rpc: "50051"
    metrics: "9100"
  serviceMonitor:
    enabled: true

listener:
  enabled: false
  nameOverride:
  image:
    name: ghcr.io/zama-ai/fhevm-coprocessor
    tag: b826fbf
  replicas: 1
  env:
    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: coprocessor-db-url
          key: coprocessor-db-url
    - name: TENANT_API_KEY
      valueFrom:
        secretKeyRef:
          name: coprocessor-api-key
          key: coprocessor-api-key
  args:
    - --database-url=$(DATABASE_URL)
    - --coprocessor-api-key=$(TENANT_API_KEY)
    - --url=ws://layer1-node:8545
  ports:
    rpc: "50052"
    metrics: "9100"
  serviceMonitor:
    enabled: true

txSender:
  enabled: false
  nameOverride:
  image:
    name: ghcr.io/zama-ai/fhevm-coprocessor
    tag: db8c783
  replicas: 1
  env:
    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: coprocessor-db-url
          key: coprocessor-db-url
    - name: TX_SENDER_PRIVATE_KEY
      value: "0x8f82b3f482c19a95ac29c82cf048c076ed0de2530c64a73f2d2d7d1e64b5cc6e"
    - name: ZKPOK_MANAGER_ADDRESS
      valueFrom:
        configMapKeyRef:
          name: layer2-sc-addresses
          key: zkpok_manager.address
    - name: CIPHERTEXT_STORAGE_ADDRESS
      valueFrom:
        configMapKeyRef:
          name: layer2-sc-addresses
          key: httpz.address
  args:
    - --database-url=${DATABASE_URL}
    - --gateway-url=http://layer2-anvil-node:8546
    - --private-key=${TX_SENDER_PRIVATE_KEY}
    - --zkpok-manager-address=${ZKPOK_MANAGER_ADDRESS}
    - --ciphertext-storage-address=${CIPHERTEXT_STORAGE_ADDRESS}
  ports:
    rpc: "50052"
    metrics: "9100"
  serviceMonitor:
    enabled: false

gwListener:
  enabled: false
  nameOverride:
  image:
    name: ghcr.io/zama-ai/fhevm-coprocessor
    tag: db8c783
  replicas: 1
  env:
    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: coprocessor-db-url
          key: coprocessor-db-url
    - name: ZKPOK_MANAGER_ADDRESS
      valueFrom:
        configMapKeyRef:
          name: layer2-sc-addresses
          key: zkpok_manager.address
  args:
    - --database-url=${DATABASE_URL}
    - --gw-url=ws://layer2-anvil-node:8546
    - --zkpok-manager-address=${ZKPOK_MANAGER_ADDRESS}
  ports:
    rpc: "50052"
    metrics: "9100"
  serviceMonitor:
    enabled: false

zkProofWorker:
  enabled: false
  nameOverride:
  image:
    name: ghcr.io/zama-ai/fhevm-coprocessor
    tag: fd7f391
  replicas: 1
  env:
    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: coprocessor-db-url
          key: coprocessor-db-url
  args:
    - --pg-listen-channel="event_zkpok_new_work"
    - --pg-notify-channel="verify_proofs"
  ports:
    rpc: "50052"
    metrics: "9100"
  serviceMonitor:
    enabled: false
