config:
  enabled: true
  coprocessorKey:
    secret:
      name: coprocessor-key
      key: coprocessor.hex
  apiKey:
    secret: 
      name: coprocessor-api-key
      key: coprocessor-api-key
  database:
    secret:
      name: coprocessor-db-url
      key: coprocessor-db-url
      value: "postgresql://postgres:postgres@httpz-postgresql:5432/coprocessor"

dbMigration:
  enabled: true
  image:
    name: ghcr.io/zama-ai/fhevm-db-migration 
    tag: v0.7.0-rc1
  env:
    - name: CHAIN_ID
      value: "12345"
    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: coprocessor-db-url
          key: coprocessor-db-url
    - name: TENANT_API_KEY
      valueFrom:
        secretKeyRef:
          name: coprocessor-api-key
          key: coprocessor-api-key
    - name: ACL_CONTRACT_ADDRESS
      valueFrom:
        configMapKeyRef:
          name: layer1-sc-addresses
          key: acl.address
    - name: INPUT_VERIFIER_ADDRESS
      valueFrom:
        configMapKeyRef:
          name: layer1-sc-addresses
          key: inputverifier.address
  insertInitContainer:
    pksURL: http://minio.fhevm.svc.cluster.local:9000/kms-public/kms/PUB/PublicKey/408d8cbaa51dece7f782fe04ba0b1c1d017b1088
    sksURL: http://minio.fhevm.svc.cluster.local:9000/kms-public/kms/PUB/ServerKey/408d8cbaa51dece7f782fe04ba0b1c1d017b1088
    publicParamsURL: http://minio.fhevm.svc.cluster.local:9000/kms-public/kms/PUB/CRS/a5fedad3fd734a598fb67452099229445cb68447
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1
      memory: 4Gi

server:
  enabled: true
  nameOverride:
  image:
    name: ghcr.io/zama-ai/fhevm-coprocessor
    tag: v0.7.0-rc1
  replicas: 1
  env:
    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: coprocessor-db-url
          key: coprocessor-db-url
  args:
    - --run-server
    - --server-addr=0.0.0.0:50052
    - --coprocessor-private-key=/accounts/coprocessor.hex
  ports:
    rpc: "50051"
    metrics: "9100"
  serviceMonitor:
    enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

listener:
  enabled: true
  image:
    name: ghcr.io/zama-ai/fhevm-coprocessor
    tag: v0.7.0-rc1
  replicas: 1
  env:
    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: coprocessor-db-url
          key: coprocessor-db-url
    - name: TENANT_API_KEY
      valueFrom:
        secretKeyRef:
          name: coprocessor-api-key
          key: coprocessor-api-key
  args:
    - --database-url=$(DATABASE_URL)
    - --coprocessor-api-key=$(TENANT_API_KEY)
    - --url=ws://layer1-anvil-node:8545
  ports:
    metrics: "9100"
  serviceMonitor:
    enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

gwListener:
  enabled: true
  image:
    name: ghcr.io/zama-ai/fhevm-coprocessor
    tag: cbcd331
  replicas: 1
  env:
    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: coprocessor-db-url
          key: coprocessor-db-url
    - name: ZKPOK_MANAGER_ADDRESS
      valueFrom:
        configMapKeyRef:
          name: layer2-sc-addresses
          key: zkpok_manager.address
  args:
    - --database-url=$(DATABASE_URL)
    - --gw-url=ws://layer2-anvil-node:8546
    - --zkpok-manager-address=$(ZKPOK_MANAGER_ADDRESS)
    - --verify-proof-req-database-channel="event_zkpok_new_work"
  ports:
    metrics: "9100"
  serviceMonitor:
    enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

zkProofWorker:
  enabled: true
  image:
    name: ghcr.io/zama-ai/fhevm-coprocessor
    tag: cbcd331
  replicas: 1
  env:
    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: coprocessor-db-url
          key: coprocessor-db-url
  args:
    - --pg-listen-channel="event_zkpok_new_work"
    - --pg-notify-channel="event_zkpok_computed"
    - --pg-polling-interval=5
    - --worker-thread-count=4
  ports:
    metrics: "9100"
  serviceMonitor:
    enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 2
      memory: 4Gi

txSender:
  enabled: true
  image:
    name: ghcr.io/zama-ai/fhevm-coprocessor
    tag: cbcd331
  replicas: 1
  env:
    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: coprocessor-db-url
          key: coprocessor-db-url
    - name: TX_SENDER_PRIVATE_KEY
      value: "0x8f82b3f482c19a95ac29c82cf048c076ed0de2530c64a73f2d2d7d1e64b5cc6e"
    - name: ZKPOK_MANAGER_ADDRESS
      valueFrom:
        configMapKeyRef:
          name: layer2-sc-addresses
          key: zkpok_manager.address
    - name: CIPHERTEXT_STORAGE_ADDRESS
      value: "0xa5e1defb98EFe38EBb2D958CEe052410247F4c80"
  args:
    - --database-url=$(DATABASE_URL)
    - --gateway-url=http://layer2-anvil-node:8546
    - --private-key=$(TX_SENDER_PRIVATE_KEY)
    - --zkpok-manager-address=$(ZKPOK_MANAGER_ADDRESS)
    - --ciphertext-storage-address=$(CIPHERTEXT_STORAGE_ADDRESS)
    - --verify-proof-resp-database-channel="event_zkpok_computed"
  ports:
    metrics: "9100"
  serviceMonitor:
    enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi