repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  # S3 - MINIO
  # temporiraly we set our own minio - this should run first + copy keys then run other releases
  - name: minio
    namespace: fhevm
    chart: bitnami/minio
    version: 15.0.3
    values:
      - minio-values.yaml

  # HTTPZ postgresql    
  - name: httpz-postgresql
    namespace: httpz
    chart: bitnami/postgresql
    version: 13.0.0
    values:
      - postgresql-values.yaml

  # HTTPZ layer1-node
  - name: layer1
    namespace: httpz
    chart: "../../charts/anvil-node"
    values:
      - layer1-node-values.yaml

  - name: layer1-sc
    namespace: httpz
    chart: "../../charts/httpz-sc-deploy"
    values:
      - layer1-sc-deploy-values.yaml
    needs:
      - layer1

  - name: layer2
    namespace: httpz
    chart: "../../charts/anvil-node"
    values:
      - layer2-node-values.yaml

  - name: layer2-sc
    namespace: httpz
    chart: "../../charts/httpz-sc-deploy"
    values:
      - layer2-sc-deploy-values.yaml
    needs:
      - layer2

  # HTTPZ coprocessor
  - name: httpz-coprocessor
    namespace: httpz
    chart: "../../charts/httpz-coprocessor"
    values:
      - coprocessor-values.yaml
    needs:
      - fhevm/minio
      - httpz-postgresql
      - layer1
      - layer2
      - layer1-sc
      - layer2-sc

  ## HTTPZ relayer
  - name: httpz-relayer
    namespace: httpz
    chart: "../../charts/httpz-relayer"
    values:
      - relayer-values.yaml
    needs:
      - fhevm/minio
      - layer1
      - layer2
      - layer1-sc
      - layer2-sc
