{{- if .Values.server.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: coprocessor-server
    app.kubernetes.io/name: {{ include "serverName" . }}
  name: {{ include "serverName" . }}
spec:
  selector:
    matchLabels:
      app: coprocessor-server
      app.kubernetes.io/name: {{ include "serverName" . }}
  endpoints:
  - port: metrics
{{- end -}}