version: '3.8'
services:
  db:
    image: postgres:15.7
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  coproc:
    image: coproc:v1
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/coprocessor
    ports:
      - '50051:50051'
    command:
      - --run-bg-worker
      - --run-server
      - --server-addr=0.0.0.0:50051
volumes:
  db:
    driver: local
