{{- if .Values.kmsFaucet.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kms-faucet
    app.kubernetes.io/name: {{ include "kmsFaucetName" . }}
  name: {{ include "kmsFaucetName" . }}
  {{- with .Values.kmsFaucet.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: http
      port: {{ .Values.kmsFaucet.ports.http }}
      targetPort: {{ .Values.kmsFaucet.ports.http }}
  selector:
    app: kms-faucet
    app.kubernetes.io/name: {{ include "kmsFaucetName" . }}
  type: ClusterIP
{{- end }}
