{{- if .Values.kmsBlockchainValidator.enabled -}}
{{- if .Values.kmsBlockchainValidator.alertRules.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}-rules
  labels:
    app.kubernetes.io/component: {{ .Release.Name }}-rules
    app.kubernetes.io/part-of: mimir-rules
spec:
  groups:
    - name: blockchain-rules
      severity: warning
      rules:
        {{- if .Values.kmsBlockchainValidator.alertRules.blockchainHalt.enabled }}
        - alert: KmsBlockchainHalt
          expr: cometbft_consensus_latest_block_height{pod=~"(.+)validator(.+)",namespace="{{ .Release.Namespace }}",cluster="{{ .Values.kmsBlockchainValidator.alertRules.clusterName }}"} == 0
          for: 2m
          labels:
            {{- .Values.kmsBlockchainValidator.alertRules.blockchainHalt.labels | toYaml | nindent 12 }}
          annotations:
            summary: Kms Blockchain Halt (namespace {{`{{`}} $labels.namespace {{`}}`}}, cluster {{`{{`}} $labels.cluster {{`}}`}})
            description: "KMS Blockchain has halted\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
        {{- end }}
        {{- if .Values.kmsBlockchainValidator.alertRules.blockchainHighLatency.enabled }}
        - alert: KmsBlockchainHighLatency
          expr: rate(cometbft_consensus_height{cluster="{{ .Values.kmsBlockchainValidator.alertRules.clusterName }}",pod=~"(.+)validator(.+)"}[5m]) < {{ .Values.kmsBlockchainValidator.alertRules.blockchainHighLatency.threshold }}
          for: 5m
          labels:
            {{- .Values.kmsBlockchainValidator.alertRules.blockchainHighLatency.labels | toYaml | nindent 12 }}
          annotations:
            summary: Kms Blockchain High Latency (namespace {{`{{`}} $labels.namespace {{`}}`}}, cluster {{`{{`}} $labels.cluster {{`}}`}})
            description: "KMS Blockchain has high latency\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
        {{- end }}
        {{- if .Values.kmsBlockchainValidator.alertRules.unconfirmedTransactions.enabled }}
        - alert: KmsBlockchainUnconfirmedTransactions
          expr: cometbft_consensus_unconfirmed_txs{namespace="{{ .Release.Namespace }}",cluster="{{ .Values.kmsBlockchainValidator.alertRules.clusterName }}",pod=~"(.+)validator(.+)"} > {{ .Values.kmsBlockchainValidator.alertRules.unconfirmedTransactions.threshold }}
          for: 5m
          labels:
            {{- .Values.kmsBlockchainValidator.alertRules.unconfirmedTransactions.labels | toYaml | nindent 12 }}
          annotations:
            summary: Kms Blockchain Unconfirmed Transactions (namespace {{`{{`}} $labels.namespace {{`}}`}}, cluster {{`{{`}} $labels.cluster {{`}}`}})
            description: "KMS Blockchain has more than {{ .Values.kmsBlockchainValidator.alertRules.unconfirmedTransactions.threshold }} unconfirmed transactions\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
        {{- end }}
{{- end }}
{{- end }}

