{{- if .Values.kmsBlockchainNetworkSetup.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: kms-blockchain-network-setup
    app.kubernetes.io/name: {{ include "kmsBlockchainValidatorName" . }}-network-setup
  name: {{ include "kmsBlockchainValidatorName" . }}-network-setup
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "1"
spec:
  template:
    metadata:
      labels:
        app: kms-blockchain-network-setup
        app.kubernetes.io/name: {{ include "kmsBlockchainValidatorName" . }}-network-setup
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/kms-blockchain-network-setup-config.yaml") . | sha256sum }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "kmsBlockchainValidatorName" . }}-network-setup
      containers:
        - name: kms-blockchain-network-setup
          image: {{ .Values.kmsBlockchainNetworkSetup.image.name }}:{{ .Values.kmsBlockchainNetworkSetup.image.tag }}
          command: ["/bin/sh", "-c"]
          args:
            - '/opt/setup_network.sh'
            {{- range .Values.kmsBlockchainNetworkSetup.genesisAccounts }}
            - {{ . | quote }}
            {{- end }}
          env:
            - name: WASMD_KEYRING_BACKEND
              value: "test"
          workingDir: /root/
          volumeMounts:
            - mountPath: /root/
              name: workdir
            - mountPath: /opt/setup_network.sh
              subPath: setup_network.sh
              name: config-files
      restartPolicy: Never
      imagePullSecrets:
        - name: registry-credentials
      volumes:
        - name: config-files
          configMap:
            name: {{ include "kmsBlockchainValidatorName" . }}-network-setup
            defaultMode: 0777
            items:
              - key: "setup_network.sh"
                path: "setup_network.sh"
        - name: workdir
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kmsBlockchainValidatorName" . }}-network-setup
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "1"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kmsBlockchainValidatorName" . }}-config-writer
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "1"
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "watch", "list", "create", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kmsBlockchainValidatorName" . }}-config-writer
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "1"
subjects:
  - kind: ServiceAccount
    name: {{ include "kmsBlockchainValidatorName" . }}-network-setup
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "kmsBlockchainValidatorName" . }}-config-writer
  apiGroup: rbac.authorization.k8s.io
{{- end }}
