{{- if .Values.kmsBlockchainBootnode.enabled -}}
{{- $kmsBlockchainBootnodeName := include "kmsBlockchainBootnodeName" . -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: kms-blockchain-bootnode
    app.kubernetes.io/name: {{ $kmsBlockchainBootnodeName }}
  name: {{ $kmsBlockchainBootnodeName }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/kms-blockchain-bootnode-config.yaml") . | sha256sum }}
spec:
  replicas: {{ .Values.kmsBlockchainBootnode.replicas }}
  selector:
    matchLabels:
      app: kms-blockchain-bootnode
  serviceName: {{ $kmsBlockchainBootnodeName }}
  template:
    metadata:
      labels:
        app: kms-blockchain-bootnode
        app.kubernetes.io/name: {{ $kmsBlockchainBootnodeName }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/kms-blockchain-bootnode-config.yaml") . | sha256sum }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      subdomain: {{ $kmsBlockchainBootnodeName }}
      containers:
        - name: kms-blockchain-bootnode
          image: {{ .Values.kmsBlockchainBootnode.image.name }}:{{ .Values.kmsBlockchainBootnode.image.tag }}
          command: ["sh", "-c"]
          args:
            - "/opt/start-bootnode.sh"
          env:
            - name: POD_INDEX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
            {{- if .Values.kmsBlockchainBootnode.persistentPeers }}
            - name: PERSISTENT_PEERS
              value: {{ .Values.kmsBlockchainBootnode.persistentPeers | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.kmsBlockchainBootnode.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: {{ .Values.kmsBlockchainBootnode.healthcheck.path }}
              port: {{ .Values.kmsBlockchainBootnode.healthcheck.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
          ports:
            {{- range $portName, $portNumber := .Values.kmsBlockchainBootnode.exposedPorts }}
            - name: {{ $portName }}
              containerPort: {{ $portNumber }}
            {{- end }}
          workingDir: /root/
          volumeMounts:
            - mountPath: /bootnode-keys
              name: bootnode-keys
              readOnly: true
            - mountPath: /root/
              name: workdir
            - mountPath: /root/.wasmd/config/genesis.json
              subPath: genesis.json
              name: genesis
            - mountPath: /root/.wasmd/config/config.toml
              subPath: config.toml
              name: config-files
            - mountPath: /root/.wasmd/config/app.toml
              subPath: app.toml
              name: config-files
            - mountPath: /opt/start-bootnode.sh
              subPath: start-bootnode.sh
              name: config-files
      restartPolicy: Always
      imagePullSecrets:
        - name: registry-credentials
      volumes:
        - name: workdir
          emptyDir: {}
        - name: bootnode-keys
          secret:
            secretName: {{ include "kmsBlockchainBootnodeName" . }}
        - name: config-files
          configMap:
            # Provide the name of the ConfigMap you want to mount.
            name: {{ $kmsBlockchainBootnodeName }}-config
            defaultMode: 0777
            # An array of keys from the ConfigMap to create as files
            items:
            - key: "config.toml"
              path: "config.toml"
            - key: "app.toml"
              path: "app.toml"
            - key: "start-bootnode.sh"
              path: "start-bootnode.sh"
        - name: genesis
          configMap:
            name: {{ include "kmsBlockchainRPCGenesisConfigmapName" . }}
            defaultMode: 0777
            items:
              - key: "genesis.json"
                path: "genesis.json"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        labels:
          app: data
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.kmsBlockchainBootnode.storage.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.kmsBlockchainBootnode.storage.capacity }}
{{- end -}}
