{{- if .Values.kmsBlockchainValidator.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kms-blockchain-validator
    app.kubernetes.io/name: {{ include "kmsBlockchainValidatorName" . }}
  name: {{ include "kmsBlockchainValidatorName" . }}
spec:
  clusterIP: None
  ports:
    {{- range $portName, $portNumber := .Values.kmsBlockchainValidator.exposedPorts }}
    - name: {{ $portName }}
      port: {{ $portNumber }}
      targetPort: {{ $portNumber }}
    {{- end }}
  selector:
    app: kms-blockchain-validator
    app.kubernetes.io/name: {{ include "kmsBlockchainValidatorName" . }}
{{- end -}}
