{{- if .Values.kmsBlockchainBootnode.enabled -}}
{{- $kmsBlockchainBootnodeName := include "kmsBlockchainBootnodeName" . }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kms-blockchain-bootnode
    app.kubernetes.io/name: {{ $kmsBlockchainBootnodeName }}
  name: {{ $kmsBlockchainBootnodeName }}
spec:
  clusterIP: None
  ports:
    {{- range $portName, $portNumber := .Values.kmsBlockchainBootnode.exposedPorts }}
    - name: {{ $portName }}
      port: {{ $portNumber }}
      targetPort: {{ $portNumber }}
    {{- end }}
  selector:
    app: kms-blockchain-bootnode
    app.kubernetes.io/name: {{ $kmsBlockchainBootnodeName }}
---
{{- range $i := until (int .Values.kmsBlockchainBootnode.replicas) }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kms-blockchain-bootnode-{{ $i }}
  name: {{ $kmsBlockchainBootnodeName }}-{{ $i }}
spec:
  clusterIP: None
  ports:
    {{- range $portName, $portNumber := $.Values.kmsBlockchainBootnode.exposedPorts }}
    - name: {{ $portName }}
      port: {{ $portNumber }}
      targetPort: {{ $portNumber }}
    {{- end }}
  selector:
    app: kms-blockchain-bootnode
    app.kubernetes.io/name: {{ $kmsBlockchainBootnodeName }}
    statefulset.kubernetes.io/pod-name: {{ $kmsBlockchainBootnodeName }}-{{ $i }}
{{- end -}}
{{- end -}}
