name: Pull request tests (contracts)

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: large_ubuntu_32
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ matrix.node-version }}
      - run: cp ./contracts/.env.example ./contracts/.env
      - run: npm --prefix ./contracts ci --include=optional
      - run: npm --prefix ./contracts run prettier:check
      - name: "npm CI test"
        run: npm --prefix ./contracts run test:mock
